service: e-commerce-be

useDotenv: true

plugins:
  - serverless-offline
  - serverless-jetpack

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:AWS_PROFILE_ID}
  timeout: 15

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'