Resources:
  DBClusterSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: AuroraDBSecret
      Description: "Secret for Aurora Serverless DB credentials"
      SecretString: !Sub |
        {
          "username": "${env:DB_MASTER_USERNAME_${self:provider.stage}}",
          "password": "${env:DB_MASTER_PASSWORD_${self:provider.stage}}",
          "engine": "postgres",
          "host": "${AuroraDBCluster.Endpoint.Address}",
          "port": 5432,
          "dbname": "${env:DB_NAME}"
        }

Outputs:
  DBSecretArn:
    Value: !Ref DBClusterSecret
    Export:
      Name: AuroraDBSecretArn
